
import type { Alumnus, Event, ProfileUpdateRequest, NewsArticle, Job, MentorshipRequest } from './types';

export const alumni: Alumnus[] = [
  {
    id: 1,
    name: 'Alex Massy',
    email: 'alex.massy@example.com',
    graduationYear: 2018,
    major: 'Computer Science',
    company: 'JP Morgan',
    jobTitle: 'Software Engineer',
    location: 'New York, NY',
    skills: ['Java', 'Python', 'SQL'],
    avatarUrl: 'https://picsum.photos/id/301/100/100',
    yearsOfExperience: 6,
    availability: 'Passive',
  },
  {
    id: 2,
    name: 'Lakshya Jangra',
    email: 'lakshya.jangra@example.com',
    graduationYear: 2019,
    major: 'Electrical Engineering',
    company: 'Nvidia',
    jobTitle: 'Hardware Engineer',
    location: 'Santa Clara, CA',
    skills: ['Verilog', 'SystemVerilog', 'C++'],
    avatarUrl: 'https://picsum.photos/id/302/100/100',
    yearsOfExperience: 5,
    availability: 'Active',
  },
  {
    id: 3,
    name: 'Aryan Dahiya',
    email: 'aryan.dahiya@example.com',
    graduationYear: 2017,
    major: 'Computer Science',
    company: 'Google',
    jobTitle: 'Product Manager',
    location: 'Mountain View, CA',
    skills: ['Product Strategy', 'Agile', 'Market Research'],
    avatarUrl: 'https://picsum.photos/id/303/100/100',
    yearsOfExperience: 7,
    availability: 'Not looking',
  },
  {
    id: 4,
    name: 'Nikhil Bokaria',
    email: 'nikhil.bokaria@example.com',
    graduationYear: 2016,
    major: 'Business Administration',
    company: 'IBM',
    jobTitle: 'Consultant',
    location: 'Austin, TX',
    skills: ['Management Consulting', 'Business Analysis', 'IT Strategy'],
    avatarUrl: 'https://picsum.photos/id/304/100/100',
    yearsOfExperience: 8,
    availability: 'Passive',
  },
  {
    id: 5,
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    graduationYear: 2018,
    major: 'Computer Science',
    company: 'Tech Solutions Inc.',
    jobTitle: 'Software Engineer',
    location: 'San Francisco, CA',
    skills: ['React', 'Node.js', 'TypeScript'],
    avatarUrl: 'https://picsum.photos/id/1027/100/100',
    yearsOfExperience: 6,
    availability: 'Passive',
  },
  {
    id: 6,
    name: 'John Smith',
    email: 'john.smith@example.com',
    graduationYear: 2016,
    major: 'Marketing',
    company: 'Creative Minds Agency',
    jobTitle: 'Marketing Manager',
    location: 'New York, NY',
    skills: ['SEO', 'Content Marketing', 'Social Media'],
    avatarUrl: 'https://picsum.photos/id/1005/100/100',
    yearsOfExperience: 8,
    availability: 'Active',
  },
];

export const events: Event[] = [
  {
    id: 1,
    title: 'MAIT Annual Alumni Reunion 2024',
    date: '2024-10-26T18:00:00',
    type: 'Reunion',
    location: 'MAIT Campus, New Delhi',
    description: 'Join us for our biggest event of the year! Reconnect with old friends, network with fellow alumni, and celebrate our shared history.',
    imageUrl: 'https://picsum.photos/600/400?random=1',
  },
  {
    id: 2,
    title: 'Webinar: AI in the Modern Workplace',
    date: '2024-09-15T14:00:00',
    type: 'Webinar',
    location: 'Online',
    description: 'A deep dive into how Artificial Intelligence is transforming industries, featuring guest speaker and MAIT alumnus, Aryan Dahiya (Google).',
    imageUrl: 'https://picsum.photos/600/400?random=2',
  },
  {
    id: 3,
    title: 'Student-Alumni Mentorship Kick-off',
    date: '2024-09-05T10:00:00',
    type: 'Mentorship Program',
    location: 'MAIT Library, Room 301',
    description: 'Our flagship mentorship program begins! Mentors and mentees will meet for the first time and set goals for the upcoming year.',
    imageUrl: 'https://picsum.photos/600/400?random=3',
  },
  {
    id: 4,
    title: 'Tech Industry Networking Night',
    date: '2024-11-12T19:00:00',
    type: 'Networking',
    location: 'Delhi Tech Hub',
    description: 'An exclusive event for MAIT alumni and students interested in the tech industry. Build connections that can shape your career.',
    imageUrl: 'https://picsum.photos/600/400?random=4',
  },
];

export const updateRequests: ProfileUpdateRequest[] = [
  {
    id: 1,
    alumnusName: 'John Smith',
    alumnusId: 2,
    fieldName: 'Job Title',
    oldValue: 'Marketing Manager',
    newValue: 'Senior Marketing Director',
    requestDate: '2024-07-28',
  },
  {
    id: 2,
    alumnusName: 'Jane Doe',
    alumnusId: 1,
    fieldName: 'Company',
    oldValue: 'Tech Solutions Inc.',
    newValue: 'Innovate Corp',
    requestDate: '2024-07-27',
  },
    {
    id: 3,
    alumnusName: 'Michael Brown',
    alumnusId: 4,
    fieldName: 'Skills',
    oldValue: 'Investment Management, Risk Analysis',
    newValue: 'Investment Management, Risk Analysis, Algorithmic Trading',
    requestDate: '2024-07-26',
  },
];

export const news: NewsArticle[] = [
  {
    id: 1,
    title: 'MAIT\'s Annual Tech Fest "TechSurge 2024" a Resounding Success',
    category: 'Campus Events',
    date: '2024-08-20',
    imageUrl: 'https://picsum.photos/600/400?random=5',
    description: 'TechSurge 2024, the annual technical festival of MAIT, saw record participation with over 50 events, workshops, and competitions.',
  },
  {
    id: 2,
    title: 'Alumnus Rohan Verma (CSE, 2012) appointed as CTO at Innovate AI',
    category: 'Alumni Achievement',
    date: '2024-08-18',
    imageUrl: 'https://picsum.photos/600/400?random=6',
    description: 'Rohan Verma, a proud alumnus, takes the helm as Chief Technology Officer at a leading AI startup, making the MAIT community proud.',
  },
  {
    id: 3,
    title: 'Record-Breaking Placements for the Graduating Batch of 2024',
    category: 'Placements',
    date: '2024-08-12',
    imageUrl: 'https://picsum.photos/600/400?random=7',
    description: 'The 2024 batch has set a new placement record with 95% of students placed in top companies with highest package reaching 50 LPA.',
  },
  {
    id: 4,
    title: 'New Centre for Robotics & Automation Inaugurated on Campus',
    category: 'Campus News',
    date: '2024-08-05',
    imageUrl: 'https://picsum.photos/600/400?random=8',
    description: 'MAIT has inaugurated a new state-of-the-art Center for Robotics and Automation to foster research and innovation.',
  },
];

export const jobs: Job[] = [
  {
    id: 1,
    title: 'Software Development Engineer',
    company: 'Amazon',
    location: 'Noida, India',
    type: 'Full-time',
    industry: 'E-commerce',
    postedDate: '2024-08-15',
    description: 'Join Amazon\'s core development team to build scalable, distributed systems. Requires strong knowledge of data structures and algorithms.',
  },
  {
    id: 2,
    title: 'Data Science Intern',
    company: 'Microsoft',
    location: 'Hyderabad, India',
    type: 'Internship',
    industry: 'Technology',
    postedDate: '2024-08-20',
    description: 'Work on real-world data science problems, develop machine learning models, and contribute to products that impact millions of users.',
  },
  {
    id: 3,
    title: 'Business Analyst',
    company: 'Zomato',
    location: 'Gurugram, India',
    type: 'Full-time',
    industry: 'Food Tech',
    postedDate: '2024-08-18',
    description: 'Analyze business processes and data to provide insights that drive strategic decisions. Work cross-functionally with product and engineering teams.',
  },
  {
    id: 4,
    title: 'Marketing Intern',
    company: 'Adobe',
    location: 'Noida, India',
    type: 'Internship',
    industry: 'Software',
    postedDate: '2024-8-22',
    description: 'Support the marketing team in executing campaigns, creating content, and analyzing market trends for Adobe\'s creative suite.',
  },
  {
    id: 5,
    title: 'Site Reliability Engineer',
    company: 'Google',
    location: 'Bengaluru, India',
    type: 'Full-time',
    industry: 'Technology',
    postedDate: '2024-08-12',
    description: 'Ensure that Google\'s services are reliable and scalable. This role combines software engineering and systems administration.',
  },
];


export const mentorshipRequests: MentorshipRequest[] = [
  {
    id: 1,
    studentName: 'Amit Kumar',
    studentId: 101,
    mentorName: 'Alex Massy',
    mentorId: 1,
    requestDate: '2024-08-25',
    status: 'Pending',
    message: 'Hi Alex, I am a final year CSE student and very interested in a career in financial technology. Your experience at JP Morgan is very impressive, and I would be grateful for your guidance.'
  },
  {
    id: 2,
    studentName: 'Priya Singh',
    studentId: 102,
    mentorName: 'Aryan Dahiya',
    mentorId: 3,
    requestDate: '2024-08-24',
    status: 'Pending',
    message: 'Hello Mr. Dahiya, I admire your journey to becoming a Product Manager at Google. I am exploring a career in product management and would love to learn from your experience.'
  },
  {
    id: 3,
    studentName: 'Rahul Sharma',
    studentId: 103,
    mentorName: 'Lakshya Jangra',
    mentorId: 2,
    requestDate: '2024-08-23',
    status: 'Accepted',
    message: 'Hi Lakshya, I am passionate about hardware engineering and your work at Nvidia is inspiring. Could I connect with you to learn more about the field?'
  },
   {
    id: 4,
    studentName: 'Sneha Gupta',
    studentId: 104,
    mentorName: 'Nikhil Bokaria',
    mentorId: 4,
    requestDate: '2024-08-22',
    status: 'Declined',
    message: 'Respected Mr. Bokaria, I am a business student interested in consulting. I saw your profile on the alumni portal and would be honored to have you as my mentor.'
  }
];
