import type { Alumnus, Event, ProfileUpdateRequest } from './types';

export const alumni: Alumnus[] = [
  {
    id: 1,
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    graduationYear: 2018,
    major: 'Computer Science',
    company: 'Tech Solutions Inc.',
    jobTitle: 'Software Engineer',
    location: 'San Francisco, CA',
    skills: ['React', 'Node.js', 'TypeScript'],
    avatarUrl: 'https://picsum.photos/id/1027/100/100',
    yearsOfExperience: 6,
    availability: 'Passive',
  },
  {
    id: 2,
    name: 'John Smith',
    email: 'john.smith@example.com',
    graduationYear: 2016,
    major: 'Marketing',
    company: 'Creative Minds Agency',
    jobTitle: 'Marketing Manager',
    location: 'New York, NY',
    skills: ['SEO', 'Content Marketing', 'Social Media'],
    avatarUrl: 'https://picsum.photos/id/1005/100/100',
    yearsOfExperience: 8,
    availability: 'Active',
  },
  {
    id: 3,
    name: 'Emily White',
    email: 'emily.white@example.com',
    graduationYear: 2020,
    major: 'Data Science',
    company: 'Data Insights LLC',
    jobTitle: 'Data Analyst',
    location: 'Chicago, IL',
    skills: ['Python', 'SQL', 'Tableau'],
    avatarUrl: 'https://picsum.photos/id/1011/100/100',
    yearsOfExperience: 4,
    availability: 'Not looking',
  },
  {
    id: 4,
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    graduationYear: 2015,
    major: 'Finance',
    company: 'Capital Investments',
    jobTitle: 'Financial Advisor',
    location: 'Boston, MA',
    skills: ['Investment Management', 'Risk Analysis'],
    avatarUrl: 'https://picsum.photos/id/1025/100/100',
    yearsOfExperience: 9,
    availability: 'Passive',
  },
  {
    id: 5,
    name: 'Sarah Green',
    email: 'sarah.green@example.com',
    graduationYear: 2022,
    major: 'Graphic Design',
    company: 'Pixel Perfect',
    jobTitle: 'UI/UX Designer',
    location: 'Austin, TX',
    skills: ['Figma', 'Adobe XD', 'User Research'],
    avatarUrl: 'https://picsum.photos/id/102/100/100',
    yearsOfExperience: 2,
    availability: 'Active',
  },
];

export const events: Event[] = [
  {
    id: 1,
    title: 'Annual Alumni Reunion 2024',
    date: '2024-10-26T18:00:00',
    type: 'Reunion',
    location: 'Grand Ballroom, University Campus',
    description: 'Join us for our biggest event of the year! Reconnect with old friends, network with fellow alumni, and celebrate our shared history.',
    imageUrl: 'https://picsum.photos/600/400?random=1',
  },
  {
    id: 2,
    title: 'Webinar: AI in the Modern Workplace',
    date: '2024-09-15T14:00:00',
    type: 'Webinar',
    location: 'Online',
    description: 'A deep dive into how Artificial Intelligence is transforming industries, featuring guest speaker and alumnus, Dr. Alan Grant.',
    imageUrl: 'https://picsum.photos/600/400?random=2',
  },
  {
    id: 3,
    title: 'Student-Alumni Mentorship Kick-off',
    date: '2024-09-05T10:00:00',
    type: 'Mentorship Program',
    location: 'University Library, Room 301',
    description: 'Our flagship mentorship program begins! Mentors and mentees will meet for the first time and set goals for the upcoming year.',
    imageUrl: 'https://picsum.photos/600/400?random=3',
  },
  {
    id: 4,
    title: 'Tech Industry Networking Night',
    date: '2024-11-12T19:00:00',
    type: 'Networking',
    location: 'Downtown Tech Hub',
    description: 'An exclusive event for alumni and students interested in the tech industry. Build connections that can shape your career.',
    imageUrl: 'https://picsum.photos/600/400?random=4',
  },
];

export const updateRequests: ProfileUpdateRequest[] = [
  {
    id: 1,
    alumnusName: 'John Smith',
    alumnusId: 2,
    fieldName: 'Job Title',
    oldValue: 'Marketing Manager',
    newValue: 'Senior Marketing Director',
    requestDate: '2024-07-28',
  },
  {
    id: 2,
    alumnusName: 'Jane Doe',
    alumnusId: 1,
    fieldName: 'Company',
    oldValue: 'Tech Solutions Inc.',
    newValue: 'Innovate Corp',
    requestDate: '2024-07-27',
  },
    {
    id: 3,
    alumnusName: 'Michael Brown',
    alumnusId: 4,
    fieldName: 'Skills',
    oldValue: 'Investment Management, Risk Analysis',
    newValue: 'Investment Management, Risk Analysis, Algorithmic Trading',
    requestDate: '2024-07-26',
  },
];
